apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l8o61hcz2-python-gitops
  description: This is GitOps manifest for l8o61hcz2-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=l8o61hcz2-python
    backstage.io/kubernetes-id: l8o61hcz2-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l8o61hcz2-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l8o61hcz2-python
